/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csps;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        CSPS_test csps = new CSPS_test();
        csps.main(args);

    }
}
